#!/bin/sh
#########################################################
#Introduction:
# This is a configuration file for EDC Backup tools
## If you have more than one project at the same server
# Just copy this file and rename it to what ever you want
# and change the vars to suite the other project needs
########################################################
# special vars rules:
# If you have more than one project on the same server
# Set the Rsync_key, Back_server, Back_user, Remot_dir
# only once in all the templates ..
#########################################################
#
# project name:
Prj_name="suzarian"
# Project Directories to backup separate with a single space:
Prj_dirs="/home/ahmadsaif/Stars"
# Mysql user prefare to be root :
Prj_mysql_user="root"
# Mysql user password:
Prj_mysql_pass="root"
# Mysql data base separate with a single space:
Prj_mysql_dbs="bacula"
# The backup destination dir:
Back_dir="/home/ahmadsaif/backup"
# The remote backup server:
Back_server="172.16.3.15"
# The remote user on the Backup server
Back_user="ahmad"
# The remote backup destination on the Backup server
Remot_dir="/home/backup"

. /home/ahmadsaif/workspace/masterback.sh
