#!/bin/bash
# Part of backup-tools
#
# Backup configuration template for projects
#
# Usage instructions:
# 
#   1. Make a copy of it with your project name
#
#        $: cp project_template projects-conf/<your-project-name>
#
#   2. Review & change all the configuration variables below
#
#   3. Make it executable: chmod +x projects-config/<your-project-name>
#
#   4. Execute it and verify that your project has been backed up correctly
#

##
# Goto backup-tools root directory
if [ -n "$MAKE_PROJECT_BACKUP" ]; then
	# We are being run using `make-project-backup.sh`
	ROOT_DIR=`dirname "$0"`
else
	# We are being run directly
	ROOT_DIR=`dirname "$0"`/..
fi;
cd $ROOT_DIR

##############################################################################
# CONFIGURATION VARIABLES
##############################################################################
#
# Load the defaults
. projects-conf/defaults

###
# Project name. Should only contain alpha numeric characters
PROJECT_NAME=""

###
# Project directories to backup, space separated
#
# If a directory contains a space it must be escaped. Example:
#
#   PROJECT_DIRECTORIES="/path/to/dir1 /path/to/dir\ 2\ with\ spaces /path/to/dir3"
#
PROJECT_DIRECTORIES=""

###
# MySQL databases to backup, space separated
#
# Example:
#
#   PROJECT_MYSQL_DATABASES="hawaa_world jawaly cas"
#
PROJECT_MYSQL_DATABASES=""

###
# E-mails of project owners, space separated
#
# Example:
#
#   PROJECT_OWNERS="first.person@egyptdc.com second.person@egyptdc.com"
#
PROJECT_OWNERS=""

##############################################################################
# MAIN
##############################################################################

. make-project-backup.sh